name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --ignore=E501,F401

      - name: Build Docker image
        run: docker build -t bloggervikash/workerlly:latest .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push bloggervikash/workerlly:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_DROPLET_SSH_KEY }}

      - name: Add DigitalOcean Droplet's SSH key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DO_DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean Droplet
        env:
          DO_DROPLET_IP: ${{ secrets.DO_DROPLET_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ env.DO_DROPLET_IP }} << 'EOF'
            docker pull bloggervikash/workerlly:latest
            docker stop workerlly || true
            docker rm workerlly || true
            docker run -d -p 8000:8000 --name workerlly bloggervikash/workerlly:latest
          EOF
